# using gradle as build tool ..
image: qlik/gradle
 
pipelines:
  default:
    - step:
        script:
          - cd ./server
          - ./gradlew clean
          - ./gradlew clean build buildFrontend